spring.application.name=todo-app

spring.datasource.url=jdbc:h2:mem:tododb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=mapa
spring.datasource.password=mapa

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=9b4445c563adb6e49cbc2aecaaebd7033c843135519f519560edc2b8b130cdb5
jwt.expiration=3600000